# Generated by Django 2.2.2 on 2020-06-03 21:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTextModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='hh', max_length=250)),
                ('description', models.CharField(blank=True, default='f', max_length=2500)),
                ('content', models.TextField(default='f')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('basetextmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseTextModel')),
                ('course_type', models.CharField(choices=[('premium', 'premium'), ('authorized', 'authorized')], db_index=True, default=('premium', 'premium'), max_length=20, verbose_name='course type - free or premium')),
            ],
            bases=('api.basetextmodel',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basetextmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseTextModel')),
            ],
            bases=('api.basetextmodel',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user_pics')),
                ('user_courses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('basetextmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseTextModel')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_for_lesson', to='api.Course')),
            ],
            bases=('api.basetextmodel',),
        ),
    ]
