TEMPLATES_ROOT = "static"

TEMPLATES_COURSES = f"{TEMPLATES_ROOT}/courses_and_lessons"
TEMPLATES_INFO = f"{TEMPLATES_ROOT}/info"
TEMPLATES_USERS = f"{TEMPLATES_ROOT}/users"
TEMPLATES_POSTS = f"{TEMPLATES_ROOT}/blog"


COURSES_PAGE = f'{TEMPLATES_COURSES}/courses.html',
SINGLE_LESSON_PAGE = f'{TEMPLATES_COURSES}/single_lesson.html'
SINGLE_COURSE_PAGE = f'{TEMPLATES_COURSES}/single_course.html'

LOGIN_PAGE = f'{TEMPLATES_USERS}/login.html'
SIGNUP_PAGE = f'{TEMPLATES_USERS}/signup.html'
USER_CABINET_PAGE =  f'{TEMPLATES_USERS}/user_cabinet.html'


INDEX_PAGE = f"{TEMPLATES_INFO}/index.html"
ENTER_PAGE = f"{TEMPLATES_USERS}/enter_choice.html"

POSTS_PAGE = f'{TEMPLATES_POSTS}/posts.html'
SINGLE_POST_PAGE = f"{TEMPLATES_POSTS}/single_post.html"