# Generated by Django 2.2.2 on 2019-10-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_status',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_status',
        ),
    ]
