# Generated by Django 3.0.6 on 2020-05-29 10:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_auto_20191030_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36), size=None),
        ),
    ]
